CREATE TABLE `Passenger` (
     `passengerId` varchar(50) NOT NULL,
     `userId` varchar(50) DEFAULT NULL,
     `ownerUserId` varchar(50) DEFAULT NULL,
     `title` enum('Dr.','Ms.','Mr.','Miss.','Mrs.','Mstr.','Prof','Rev.') DEFAULT NULL,
     `firstName` varchar(30) NOT NULL,
     `lastName` varchar(30) NOT NULL,
     `dateOfBirth` date NOT NULL,
     `gender` enum('Male','Female','Non-Binary','Other') DEFAULT NULL,
     `phoneNumber` varchar(20) DEFAULT NULL,
     `email` varchar(100) DEFAULT NULL,
     `DLNumber` int DEFAULT NULL,
     `DLState` char(2) DEFAULT NULL,
     `passportNumber` varchar(20) DEFAULT NULL,
     `passportCountryCode` char(2) DEFAULT NULL,
     `passportExpirationDate` date DEFAULT NULL,
     `placeOfBirth` varchar(30) DEFAULT NULL,
     `nationality` char(2) DEFAULT NULL,
     `passengerType` enum('Adult','Child','Infant') NOT NULL DEFAULT 'Adult',
     PRIMARY KEY (`passengerId`),
     KEY `FK_Passenger_User` (`userId`),
     KEY `fk_passenger_dlstate` (`DLState`),
     KEY `fk_passenger_passport_country` (`passportCountryCode`),
     KEY `fk_passenger_nationality` (`nationality`),
     KEY `FK_Passenger_OwnerUser` (`ownerUserId`),
     CONSTRAINT `fk_passenger_dlstate` FOREIGN KEY (`DLState`) REFERENCES `States` (`code`) ON DELETE RESTRICT ON UPDATE CASCADE,
     CONSTRAINT `fk_passenger_nationality` FOREIGN KEY (`nationality`) REFERENCES `Countries` (`code`) ON DELETE RESTRICT ON UPDATE CASCADE,
     CONSTRAINT `fk_passenger_owner_user` FOREIGN KEY (`ownerUserId`) REFERENCES `Users` (`userId`) ON DELETE RESTRICT ON UPDATE CASCADE,
     CONSTRAINT `fk_passenger_passport_country` FOREIGN KEY (`passportCountryCode`) REFERENCES `Countries` (`code`) ON DELETE RESTRICT ON UPDATE CASCADE,
     CONSTRAINT `fk_passenger_user` FOREIGN KEY (`userId`) REFERENCES `Users` (`userId`) ON DELETE RESTRICT ON UPDATE CASCADE,
     CONSTRAINT `Passenger_chk_1` CHECK ((`email` like _utf8mb4'%@%.%'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci